name: Test Coverage

on:
  workflow_call:

jobs:
  coverage:
    runs-on: ubuntu-latest
    container: davorg/perl-coveralls:latest
    name: Test coverage
    steps:
      - uses: actions/checkout@v4

      - name: Install modules
        run: cpanm -n --installdeps .

      - name: Run tests with coverage
        run: |
          cd tests
          PERL5OPT=-MDevel::Cover prove *.t
          cover

      - name: Total coverage percentage
        run: cover | perl -ne 'print +(split)[-1], "\n" if /^Total\b/'
